### ISSUE TITLE
Link shouldn't use CXX/g++ if all sources are plain C files

### ISSUE THREAD

**Issue by kanaka** [c3d/build#6]
I'm running into a problem where I specify `-m32` for CFLAGS and LDFLAGS. This works fine for the compilation, but when it comes time to link, I get this complaint:

```
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/libstdc++.so when searching for -lstdc++
```

This is due to the fact that g++ is being used to link instead of gcc which implies libstdc++, but all my source files were plain C files so the logic could detect this and use gcc instead for the link.

**Comment by c3d** [comment]
Could you check that the commit above fixes the problem for you. If not, reopen.
